<?php
			
/* Generated by the CoffeeCup Web Editor - www.coffeecup.com */
			
/*
Description...
			
			
			
			
@created:           10/01/2018 - 17:40:13
@today:             10/01/2018
@project:           No Project
@path:              /Users/test/Documents/web.php
			
@author:            Your name
@company:           Your company
@Copyright:         A copyright notice

@version:           $Revision:$
*/
	

?>
